# Generated by Django 4.1.5 on 2023-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0002_cattest_remove_cat_purchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattest',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cattest',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cattest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cattest',
            name='personality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cattest',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
