# Generated by Django 4.1.5 on 2023-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0003_cattest_color_cattest_gender_cattest_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cat_pics'),
        ),
    ]
