# Generated by Django 3.2.16 on 2023-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.AlterField(
            model_name='cat',
            name='dob',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
